CREATE database OLA;
USE OLA;
-- RETRIEVE ALL SUCCESSFULL BOOKINGS

CREATE VIEW SUCCESSFULL_BOOKINGS AS
SELECT * FROM BOOKINGS
 WHERE BOOKING_STATUS = 'SUCCESS';
 
 SELECT * FROM SUCCESSFULL_BOOKINGS;
 
 -- FIND THE AVERAGE RIDE DISTANCE FOR EACH VEHICLE TYPE
 
CREATE VIEW RIDE_DISTANCE_FOR_EACH_VEHICLE AS
 SELECT VEHICLE_TYPE, AVG(RIDE_DISTANCE) 
 AS AVG_DISTANCE FROM BOOKINGS
 GROUP BY VEHICLE_TYPE;

SELECT * FROM RIDE_DISTANCE_FOR_EACH_VEHICLE ;

-- GET THE TOTAL NO OF CANCELED RIDES BY CUSTOMER

CREATE VIEW CANCELED_RIDES_BY_CUSTOMER AS
SELECT count(*) AS TOTAL_CANCELED_BY_CUSTOMER
FROM BOOKINGS 
WHERE BOOKING_STATUS ='CANCELED BY CUSTOMER';

SELECT * FROM CANCELED_RIDES_BY_CUSTOMER;

-- LIST THE TOP 5 CUSTOMERS WHO BOOKED THE HIGHEST NUMBER OF RIDES

CREATE VIEW TOP_5_CUSTOMER AS
SELECT CUSTOMER_ID, COUNT(BOOKING_ID) AS TOTAL_RIDES
FROM BOOKINGS
GROUP BY CUSTOMER_ID
ORDER BY TOTAL_RIDES DESC
LIMIT 5;

SELECT * FROM TOP_5_CUSTOMER;

-- GET THE NO OF RIDES CANCELLED BY DRIVERS DUE TO PERSONAL AND CAR-RELATED ISSUES:

CREATE VIEW CANCELED_RIDES_BY_DRIVER AS
SELECT COUNT(*) 
FROM BOOKINGS
 WHERE CANCELED_RIDES_BY_DRIVER='Personal & Car related issue';

SELECT * FROM CANCELED_RIDES_BY_DRIVER ;

-- FIND THE MAXIMUM AND MINIMUM DRIVER RATINGS FOR PRIME SEDAN BOOKINGS:

CREATE VIEW MIN_MAX_DRIVER_RATING AS
SELECT MIN(DRIVER_RATINGS) AS MIN_RATING, MAX(DRIVER_RATINGS) AS MAX_RATING
FROM BOOKINGS
WHERE VEHICLE_TYPE='PRIME SEDAN';

SELECT * FROM MIN_MAX_DRIVER_RATING;

-- RETRIEVE ALL RIDES WHERE PAYMENT WAS MADE USING UPI

CREATE VIEW RIDE_PAYMENT_BY_UPI AS
SELECT * FROM BOOKINGS
WHERE PAYMENT_METHOD='UPI';

SELECT * FROM RIDE_PAYMENT_BY_UPI;

-- FIND THE AVERAGE CUSTOMER RATING PER VEHICLE TYPE:

CREATE VIEW AVG_CUSTOMER_RATING AS
SELECT VEHICLE_TYPE, AVG(CUSTOMER_RATING) FROM BOOKINGS
GROUP BY VEHICLE_TYPE;

SELECT * FROM AVG_CUSTOMER_RATING;

-- CALCULATE THE TOTAL BOOKING VALUE OF RIDES COMPLETED SUCCESSFULLY

CREATE VIEW TOTAL_SUCCESSFULL_RIDE_VALUE AS
SELECT SUM(BOOKING_VALUE) AS TOTAL_SUCCESSFUL_RIDE_VALUE
FROM BOOKINGS
WHERE BOOKING_STATUS='SUCCESS';

SELECT * FROM TOTAL_SUCCESSFULL_RIDE_VALUE;

-- LIST ALL INCOMPLETE RIDES ALONG WITH THE REASON

CREATE VIEW INCOMPLETE_RIDE_REASON AS
SELECT BOOKING_ID, INCOMPLETE_RIDES_REASON
 FROM BOOKINGS 
WHERE INCOMPLETE_RIDES='YES';

SELECT * FROM INCOMPLETE_RIDE_REASON;


-- RETRIEVE ALL ANSWERS

-- 1. RETRIEVE ALL SUCCESSFULL BOOKINGS
 SELECT * FROM SUCCESSFULL_BOOKINGS;
 
-- 2. FIND THE AVERAGE RIDE DISTANCE FOR EACH VEHICLE TYPE
SELECT * FROM RIDE_DISTANCE_FOR_EACH_VEHICLE ;

-- 3. GET THE TOTAL NO OF CANCELED RIDES BY CUSTOMER
SELECT * FROM CANCELED_RIDES_BY_CUSTOMER;

-- 4. LIST THE TOP 5 CUSTOMERS WHO BOOKED THE HIGHEST NUMBER OF RIDES
SELECT * FROM TOP_5_CUSTOMER;

-- 5. GET THE NO OF RIDES CANCELLED BY DRIVERS DUE TO PERSONAL AND CAR-RELATED ISSUES:
SELECT * FROM CANCELED_RIDES_BY_DRIVER ;

-- 6. FIND THE MAXIMUM AND MINIMUM DRIVER RATINGS FOR PRIME SEDAN BOOKINGS:
SELECT * FROM MIN_MAX_DRIVER_RATING;

-- 7. RETRIEVE ALL RIDES WHERE PAYMENT WAS MADE USING UPI
SELECT * FROM RIDE_PAYMENT_BY_UPI;

-- 8. FIND THE AVERAGE CUSTOMER RATING PER VEHICLE TYPE:
SELECT * FROM AVG_CUSTOMER_RATING;

-- 9. CALCULATE THE TOTAL BOOKING VALUE OF RIDES COMPLETED SUCCESSFULLY
SELECT * FROM TOTAL_SUCCESSFULL_RIDE_VALUE;

-- 10. LIST ALL INCOMPLETE RIDES ALONG WITH THE REASON
SELECT * FROM INCOMPLETE_RIDE_REASON;
